[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "oq-taxonomy"
dynamic = ["version"]

[project.optional-dependencies]
test = [
    "openquake.moon ~= 1.2.0",
    "pytest ~= 9.1.1",
    "requests ~= 2.34.0",
]

[tool.setuptools.packages.find]
namespaces = true
include = ["openquake*"] 

[tool.setuptools.dynamic]
version = {attr = "openquake.taxonomy.__version__"}
